//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavelyevLanguage
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }

        public string FullName => $"{FirstName} {LastName} {Patronymic}";

        public string ClientPhotoPath
        {
            get
            {
                if (PhotoPath == null)
                {
                    return null;
                }

                return PhotoPath;
            }
        }
        public string GenderCode { get; set; }
        public string GenderName
        {
            get
            {
                return Gender.Name;
            }
        }

        public DateTime? LastVisitDate
        {
            get
            {
                if (ClientService != null && ClientService.Any())
                {
                    return ClientService.Select(x => x.StartTime).Max();
                }
                else
                {
                    return null;
                }
            }
        }
        public int VisitsCount
        {
            get
            {
                if (ClientService != null)
                    return ClientService.Count();               
                else
                {
                    return 0;
                }
            }
        }

        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        //public string RegistrationDateString
        //{
        //    get
        //    { 
        //        if (RegistrationDate != null)
        //        {
        //            return RegistrationDate.ToShortDateString();
        //        }
        //        else
        //        {
        //            return "";
        //        }
        //    }
        //}
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
